package net.adhikary.mrtbuddy.model

object FareMatrix {
    private val matrix = mapOf(
        "Uttara North" to mapOf(
            "Uttara North" to 0,
            "Uttara Center" to 20,
            "Uttara South" to 20,
            "Pallabi" to 30,
            "Mirpur-11" to 30,
            "Mirpur-10" to 40,
            "Kazipara" to 40,
            "Shewrapara" to 40,
            "Agargaon" to 60,
            "Bijoy Sarani" to 60,
            "Farmgate" to 70,
            "Karwan Bazar" to 70,
            "Shahbagh" to 80,
            "Dhaka University" to 80,
            "Bangladesh Secretariat" to 100,
            "Motijheel" to 100,
            "Kamalapur" to 100
        ),
        "Uttara Center" to mapOf(
            "Uttara North" to 20,
            "Uttara Center" to 0,
            "Uttara South" to 20,
            "Pallabi" to 30,
            "Mirpur-11" to 30,
            "Mirpur-10" to 40,
            "Kazipara" to 40,
            "Shewrapara" to 40,
            "Agargaon" to 60,
            "Bijoy Sarani" to 60,
            "Farmgate" to 70,
            "Karwan Bazar" to 70,
            "Shahbagh" to 80,
            "Dhaka University" to 80,
            "Bangladesh Secretariat" to 100,
            "Motijheel" to 100,
            "Kamalapur" to 100
        ),
        "Uttara South" to mapOf(
            "Uttara North" to 20,
            "Uttara Center" to 20,
            "Uttara South" to 0,
            "Pallabi" to 20,
            "Mirpur-11" to 30,
            "Mirpur-10" to 30,
            "Kazipara" to 40,
            "Shewrapara" to 40,
            "Agargaon" to 60,
            "Bijoy Sarani" to 60,
            "Farmgate" to 70,
            "Karwan Bazar" to 70,
            "Shahbagh" to 80,
            "Dhaka University" to 80,
            "Bangladesh Secretariat" to 100,
            "Motijheel" to 100,
            "Kamalapur" to 100
        ),
        "Pallabi" to mapOf(
            "Uttara North" to 30,
            "Uttara Center" to 30,
            "Uttara South" to 20,
            "Pallabi" to 0,
            "Mirpur-11" to 20,
            "Mirpur-10" to 20,
            "Kazipara" to 30,
            "Shewrapara" to 30,
            "Agargaon" to 40,
            "Bijoy Sarani" to 50,
            "Farmgate" to 60,
            "Karwan Bazar" to 60,
            "Shahbagh" to 70,
            "Dhaka University" to 70,
            "Bangladesh Secretariat" to 80,
            "Motijheel" to 80,
            "Kamalapur" to 80
        ),
        "Mirpur-11" to mapOf(
            "Uttara North" to 30,
            "Uttara Center" to 30,
            "Uttara South" to 30,
            "Pallabi" to 20,
            "Mirpur-11" to 0,
            "Mirpur-10" to 20,
            "Kazipara" to 20,
            "Shewrapara" to 30,
            "Agargaon" to 40,
            "Bijoy Sarani" to 50,
            "Farmgate" to 60,
            "Karwan Bazar" to 60,
            "Shahbagh" to 70,
            "Dhaka University" to 70,
            "Bangladesh Secretariat" to 80,
            "Motijheel" to 80,
            "Kamalapur" to 80
        ),
        "Mirpur-10" to mapOf(
            "Uttara North" to 40,
            "Uttara Center" to 40,
            "Uttara South" to 30,
            "Pallabi" to 20,
            "Mirpur-11" to 20,
            "Mirpur-10" to 0,
            "Kazipara" to 20,
            "Shewrapara" to 20,
            "Agargaon" to 30,
            "Bijoy Sarani" to 40,
            "Farmgate" to 50,
            "Karwan Bazar" to 50,
            "Shahbagh" to 60,
            "Dhaka University" to 60,
            "Bangladesh Secretariat" to 80,
            "Motijheel" to 80,
            "Kamalapur" to 80
        ),
        "Kazipara" to mapOf(
            "Uttara North" to 40,
            "Uttara Center" to 40,
            "Uttara South" to 40,
            "Pallabi" to 30,
            "Mirpur-11" to 20,
            "Mirpur-10" to 20,
            "Kazipara" to 0,
            "Shewrapara" to 20,
            "Agargaon" to 30,
            "Bijoy Sarani" to 40,
            "Farmgate" to 50,
            "Karwan Bazar" to 50,
            "Shahbagh" to 60,
            "Dhaka University" to 60,
            "Bangladesh Secretariat" to 80,
            "Motijheel" to 80,
            "Kamalapur" to 80
        ),
        "Shewrapara" to mapOf(
            "Uttara North" to 40,
            "Uttara Center" to 40,
            "Uttara South" to 40,
            "Pallabi" to 30,
            "Mirpur-11" to 30,
            "Mirpur-10" to 20,
            "Kazipara" to 20,
            "Shewrapara" to 0,
            "Agargaon" to 20,
            "Bijoy Sarani" to 30,
            "Farmgate" to 40,
            "Karwan Bazar" to 40,
            "Shahbagh" to 50,
            "Dhaka University" to 50,
            "Bangladesh Secretariat" to 70,
            "Motijheel" to 70,
            "Kamalapur" to 70
        ),
        "Agargaon" to mapOf(
            "Uttara North" to 60,
            "Uttara Center" to 60,
            "Uttara South" to 60,
            "Pallabi" to 40,
            "Mirpur-11" to 40,
            "Mirpur-10" to 30,
            "Kazipara" to 30,
            "Shewrapara" to 20,
            "Agargaon" to 0,
            "Bijoy Sarani" to 20,
            "Farmgate" to 30,
            "Karwan Bazar" to 30,
            "Shahbagh" to 40,
            "Dhaka University" to 40,
            "Bangladesh Secretariat" to 60,
            "Motijheel" to 60,
            "Kamalapur" to 60
        ),
        "Bijoy Sarani" to mapOf(
            "Uttara North" to 60,
            "Uttara Center" to 60,
            "Uttara South" to 60,
            "Pallabi" to 50,
            "Mirpur-11" to 50,
            "Mirpur-10" to 40,
            "Kazipara" to 40,
            "Shewrapara" to 30,
            "Agargaon" to 20,
            "Bijoy Sarani" to 0,
            "Farmgate" to 20,
            "Karwan Bazar" to 20,
            "Shahbagh" to 30,
            "Dhaka University" to 30,
            "Bangladesh Secretariat" to 50,
            "Motijheel" to 50,
            "Kamalapur" to 50
        ),
        "Farmgate" to mapOf(
            "Uttara North" to 70,
            "Uttara Center" to 70,
            "Uttara South" to 70,
            "Pallabi" to 60,
            "Mirpur-11" to 60,
            "Mirpur-10" to 50,
            "Kazipara" to 50,
            "Shewrapara" to 40,
            "Agargaon" to 30,
            "Bijoy Sarani" to 20,
            "Farmgate" to 0,
            "Karwan Bazar" to 20,
            "Shahbagh" to 30,
            "Dhaka University" to 30,
            "Bangladesh Secretariat" to 40,
            "Motijheel" to 40,
            "Kamalapur" to 40
        ),
        "Karwan Bazar" to mapOf(
            "Uttara North" to 70,
            "Uttara Center" to 70,
            "Uttara South" to 70,
            "Pallabi" to 60,
            "Mirpur-11" to 60,
            "Mirpur-10" to 50,
            "Kazipara" to 50,
            "Shewrapara" to 40,
            "Agargaon" to 30,
            "Bijoy Sarani" to 20,
            "Farmgate" to 20,
            "Karwan Bazar" to 0,
            "Shahbagh" to 20,
            "Dhaka University" to 20,
            "Bangladesh Secretariat" to 30,
            "Motijheel" to 30,
            "Kamalapur" to 30
        ),
        "Shahbagh" to mapOf(
            "Uttara North" to 80,
            "Uttara Center" to 80,
            "Uttara South" to 80,
            "Pallabi" to 70,
            "Mirpur-11" to 70,
            "Mirpur-10" to 60,
            "Kazipara" to 60,
            "Shewrapara" to 50,
            "Agargaon" to 40,
            "Bijoy Sarani" to 30,
            "Farmgate" to 30,
            "Karwan Bazar" to 20,
            "Shahbagh" to 0,
            "Dhaka University" to 20,
            "Bangladesh Secretariat" to 30,
            "Motijheel" to 30,
            "Kamalapur" to 30
        ),
        "Dhaka University" to mapOf(
            "Uttara North" to 80,
            "Uttara Center" to 80,
            "Uttara South" to 80,
            "Pallabi" to 70,
            "Mirpur-11" to 70,
            "Mirpur-10" to 60,
            "Kazipara" to 60,
            "Shewrapara" to 50,
            "Agargaon" to 40,
            "Bijoy Sarani" to 30,
            "Farmgate" to 30,
            "Karwan Bazar" to 20,
            "Shahbagh" to 20,
            "Dhaka University" to 0,
            "Bangladesh Secretariat" to 20,
            "Motijheel" to 20,
            "Kamalapur" to 20
        ),
        "Bangladesh Secretariat" to mapOf(
            "Uttara North" to 100,
            "Uttara Center" to 100,
            "Uttara South" to 100,
            "Pallabi" to 80,
            "Mirpur-11" to 80,
            "Mirpur-10" to 80,
            "Kazipara" to 80,
            "Shewrapara" to 70,
            "Agargaon" to 60,
            "Bijoy Sarani" to 50,
            "Farmgate" to 40,
            "Karwan Bazar" to 30,
            "Shahbagh" to 30,
            "Dhaka University" to 20,
            "Bangladesh Secretariat" to 0,
            "Motijheel" to 20,
            "Kamalapur" to 20
        ),
        "Motijheel" to mapOf(
            "Uttara North" to 100,
            "Uttara Center" to 100,
            "Uttara South" to 100,
            "Pallabi" to 80,
            "Mirpur-11" to 80,
            "Mirpur-10" to 80,
            "Kazipara" to 80,
            "Shewrapara" to 70,
            "Agargaon" to 60,
            "Bijoy Sarani" to 50,
            "Farmgate" to 40,
            "Karwan Bazar" to 30,
            "Shahbagh" to 30,
            "Dhaka University" to 20,
            "Bangladesh Secretariat" to 20,
            "Motijheel" to 0,
            "Kamalapur" to 20
        ),
        "Kamalapur" to mapOf(
            "Uttara North" to 100,
            "Uttara Center" to 100,
            "Uttara South" to 100,
            "Pallabi" to 80,
            "Mirpur-11" to 80,
            "Mirpur-10" to 80,
            "Kazipara" to 80,
            "Shewrapara" to 70,
            "Agargaon" to 60,
            "Bijoy Sarani" to 50,
            "Farmgate" to 40,
            "Karwan Bazar" to 30,
            "Shahbagh" to 30,
            "Dhaka University" to 20,
            "Bangladesh Secretariat" to 20,
            "Motijheel" to 20,
            "Kamalapur" to 0
        )
    )

    fun getFare(from: String, to: String): Int {
        if (from.isEmpty() || to.isEmpty()) return 0

        // Try direct fare
        matrix[from]?.get(to)?.let { return it }
        // Try reverse direction (symmetric fares)
        matrix[to]?.get(from)?.let { return it }

        // If no fare found, return 0 (invalid combination)
        return 0
    }
}
